### ISSUE TITLE
Issues with TutFurnace

### ISSUE THREAD

**Issue by Nemesizz** [TheGrovesyProject101/ModdingTutorials#2]
TutFurnace:
if (direction.func_149730_j() && direction.func_149730_j()) {

should be
if (direction.func_149730_j() && !direction.func_149730_j()) {

for all 4 instances 
also

	public IIcon getIcon(int side, int meta) {
if (side == 1) {
return top;
} else if (side == 3) {
return front;
} else {
return this.blockIcon;
}
}

that wouldnt even work the way you would expect it as the front would always be south(i believe thats 3), anyways, should check side against meta instead of 3

**Comment by hihellobyeoh** [comment]
yeah i ran into this giving me problems too, i eventually just copied the vanilla furnace code and modified that by hand to get it all working right
